"""Static source registry."""

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field
import os
import re
from typing import Any
from urllib.parse import urlsplit

from newsbot.categories import CATEGORY_CRYPTO
from newsbot.categories import CATEGORY_KR_CULTURE
from newsbot.categories import CATEGORY_KR_ECONOMY
from newsbot.categories import CATEGORY_KR_LOCAL
from newsbot.categories import CATEGORY_KR_POLITICS
from newsbot.categories import CATEGORY_KR_SOCIETY
from newsbot.categories import CATEGORY_KR_SPORTS
from newsbot.categories import CATEGORY_MILITARY
from newsbot.categories import CATEGORY_TECH_IT
from newsbot.categories import CATEGORY_US_ECONOMY
from newsbot.categories import CATEGORY_US_MARKETS
from newsbot.categories import CATEGORY_US_POLITICS
from newsbot.categories import CATEGORY_US_TECHNOLOGY
from newsbot.categories import CATEGORY_US_WORLD
from newsbot.categories import HUB_GLOBAL
from newsbot.categories import HUB_KR
from newsbot.categories import HUB_US
from newsbot.config import _load_dotenv


_load_dotenv()

_ENV_TELEGRAM_CHANNEL_KEYS = (
    "NEWSBOT_TELEGRAM_NEWS_CHANNELS",
    "NEWSBOT_TELEGRAM_NEWS_CHANNEL",
    "NEWSBOT_TELEGRAM_EXTRA_CHANNELS",
)
_ENV_CHANNEL_SPLIT_PATTERN = re.compile(r"[\n,;]+")
_TELEGRAM_CHANNEL_PATTERN = re.compile(r"^[A-Za-z0-9_]{5,64}$")
BLOCKED_SOURCE_KEYS = frozenset(
    {
        "pressian-politics-rss",
        "pressian-economy-rss",
    }
)


@dataclass(frozen=True, slots=True)
class SourceDefinition:
    source_key: str
    name: str
    adapter_type: str
    category: str | None
    poll_interval_sec: int
    base_url: str
    trust_level: int
    discovery_only: bool = False
    allow_page_fetch: bool = False
    static_enabled: bool = True
    dedupe_strategy: str = "default"
    config: dict[str, Any] = field(default_factory=dict)


def _meta(
    *,
    hub: str,
    section: str,
    publisher_group: str,
    **extra: Any,
) -> dict[str, Any]:
    return {
        "hub": hub,
        "section": section,
        "publisher_group": publisher_group,
        **extra,
    }


def _rss_source(
    *,
    source_key: str,
    name: str,
    category: str | None,
    base_url: str,
    feed_url: str,
    trust_level: int,
    hub: str,
    section: str,
    publisher_group: str,
    poll_interval_sec: int = 300,
    static_enabled: bool = True,
    discovery_only: bool = False,
    allow_page_fetch: bool = True,
    **config: Any,
) -> SourceDefinition:
    return SourceDefinition(
        source_key=source_key,
        name=name,
        adapter_type="rss",
        category=category,
        poll_interval_sec=poll_interval_sec,
        base_url=base_url,
        trust_level=trust_level,
        static_enabled=static_enabled,
        discovery_only=discovery_only,
        allow_page_fetch=allow_page_fetch,
        config={
            "feed_url": feed_url,
            **_meta(
                hub=hub,
                section=section,
                publisher_group=publisher_group,
                **config,
            ),
        },
    )


def _html_source(
    *,
    source_key: str,
    name: str,
    category: str | None,
    base_url: str,
    page_url: str,
    allowed_domains: list[str],
    article_prefixes: list[str],
    trust_level: int,
    hub: str,
    section: str,
    publisher_group: str,
    poll_interval_sec: int = 600,
    max_links: int = 30,
    static_enabled: bool = True,
    discovery_only: bool = False,
    allow_page_fetch: bool = True,
    **config: Any,
) -> SourceDefinition:
    return SourceDefinition(
        source_key=source_key,
        name=name,
        adapter_type="html_discovery",
        category=category,
        poll_interval_sec=poll_interval_sec,
        base_url=base_url,
        trust_level=trust_level,
        discovery_only=discovery_only,
        allow_page_fetch=allow_page_fetch,
        static_enabled=static_enabled,
        config={
            "page_url": page_url,
            "allowed_domains": allowed_domains,
            "article_prefixes": article_prefixes,
            "max_links": max_links,
            **_meta(
                hub=hub,
                section=section,
                publisher_group=publisher_group,
                **config,
            ),
        },
    )


BASE_SOURCE_DEFINITIONS = [
    _rss_source(
        source_key="coindesk-rss",
        name="CoinDesk",
        category=CATEGORY_CRYPTO,
        base_url="https://www.coindesk.com",
        feed_url="https://www.coindesk.com/arc/outboundfeeds/rss/",
        trust_level=90,
        hub=HUB_GLOBAL,
        section="crypto",
        publisher_group="internet",
    ),
    _rss_source(
        source_key="cointelegraph-rss",
        name="Cointelegraph",
        category=CATEGORY_CRYPTO,
        base_url="https://cointelegraph.com",
        feed_url="https://cointelegraph.com/rss",
        trust_level=85,
        hub=HUB_GLOBAL,
        section="crypto",
        publisher_group="internet",
    ),
    _rss_source(
        source_key="sec-crypto-rss",
        name="SEC Crypto Filter",
        category=CATEGORY_CRYPTO,
        base_url="https://www.sec.gov",
        feed_url="https://www.sec.gov/news/pressreleases.rss",
        trust_level=95,
        hub=HUB_GLOBAL,
        section="crypto",
        publisher_group="government",
        include_keywords=[
            "crypto",
            "digital asset",
            "bitcoin",
            "ethereum",
            "token",
            "blockchain",
        ],
    ),
    _rss_source(
        source_key="techcrunch-rss",
        name="TechCrunch",
        category=CATEGORY_TECH_IT,
        base_url="https://techcrunch.com",
        feed_url="https://techcrunch.com/feed/",
        trust_level=85,
        hub=HUB_GLOBAL,
        section="technology",
        publisher_group="internet",
    ),
    _rss_source(
        source_key="arstechnica-rss",
        name="Ars Technica",
        category=CATEGORY_TECH_IT,
        base_url="https://arstechnica.com",
        feed_url="https://feeds.arstechnica.com/arstechnica/index",
        trust_level=85,
        hub=HUB_GLOBAL,
        section="technology",
        publisher_group="internet",
    ),
    _rss_source(
        source_key="defense-rss",
        name="Defense.gov",
        category=CATEGORY_MILITARY,
        base_url="https://www.defense.gov",
        feed_url="https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=945&max=20",
        trust_level=95,
        hub=HUB_GLOBAL,
        section="defense",
        publisher_group="government",
    ),
    _html_source(
        source_key="army-news",
        name="Army News",
        category=CATEGORY_MILITARY,
        base_url="https://www.army.mil/news",
        page_url="https://www.army.mil/news",
        allowed_domains=["www.army.mil", "army.mil"],
        article_prefixes=["/article/", "/news/"],
        trust_level=90,
        hub=HUB_GLOBAL,
        section="defense",
        publisher_group="government",
    ),
    _rss_source(
        source_key="federalreserve-rss",
        name="Federal Reserve",
        category=CATEGORY_US_MARKETS,
        base_url="https://www.federalreserve.gov",
        feed_url="https://www.federalreserve.gov/feeds/press_all.xml",
        trust_level=100,
        hub=HUB_US,
        section="markets",
        publisher_group="government",
    ),
    _rss_source(
        source_key="sec-rss",
        name="SEC Press Releases",
        category=CATEGORY_US_MARKETS,
        base_url="https://www.sec.gov",
        feed_url="https://www.sec.gov/news/pressreleases.rss",
        trust_level=95,
        hub=HUB_US,
        section="markets",
        publisher_group="government",
    ),
    _rss_source(
        source_key="bls-rss",
        name="BLS Latest Releases",
        category=CATEGORY_US_ECONOMY,
        base_url="https://www.bls.gov",
        feed_url="https://www.bls.gov/feed/bls_latest.rss",
        trust_level=95,
        hub=HUB_US,
        section="economy",
        publisher_group="government",
    ),
    _rss_source(
        source_key="nyt-us-rss",
        name="New York Times US",
        category=CATEGORY_US_POLITICS,
        base_url="https://www.nytimes.com",
        feed_url="https://rss.nytimes.com/services/xml/rss/nyt/US.xml",
        trust_level=95,
        hub=HUB_US,
        section="politics",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="nyt-business-rss",
        name="New York Times Business",
        category=CATEGORY_US_ECONOMY,
        base_url="https://www.nytimes.com",
        feed_url="https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
        trust_level=95,
        hub=HUB_US,
        section="economy",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="nyt-world-rss",
        name="New York Times World",
        category=CATEGORY_US_WORLD,
        base_url="https://www.nytimes.com",
        feed_url="https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
        trust_level=95,
        hub=HUB_US,
        section="world",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="nyt-technology-rss",
        name="New York Times Technology",
        category=CATEGORY_US_TECHNOLOGY,
        base_url="https://www.nytimes.com",
        feed_url="https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
        trust_level=95,
        hub=HUB_US,
        section="technology",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="wsj-world-rss",
        name="Wall Street Journal World",
        category=CATEGORY_US_WORLD,
        base_url="https://www.wsj.com",
        feed_url="https://feeds.a.dj.com/rss/RSSWorldNews.xml",
        trust_level=93,
        hub=HUB_US,
        section="world",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="wsj-markets-rss",
        name="Wall Street Journal Markets",
        category=CATEGORY_US_MARKETS,
        base_url="https://www.wsj.com",
        feed_url="https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
        trust_level=93,
        hub=HUB_US,
        section="markets",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="wapo-politics-rss",
        name="Washington Post Politics",
        category=CATEGORY_US_POLITICS,
        base_url="https://www.washingtonpost.com",
        feed_url="https://feeds.washingtonpost.com/rss/politics",
        trust_level=92,
        hub=HUB_US,
        section="politics",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="wapo-national-rss",
        name="Washington Post National",
        category=CATEGORY_US_POLITICS,
        base_url="https://www.washingtonpost.com",
        feed_url="https://feeds.washingtonpost.com/rss/national",
        trust_level=92,
        hub=HUB_US,
        section="politics",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="wapo-world-rss",
        name="Washington Post World",
        category=CATEGORY_US_WORLD,
        base_url="https://www.washingtonpost.com",
        feed_url="https://feeds.washingtonpost.com/rss/world",
        trust_level=92,
        hub=HUB_US,
        section="world",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="wapo-business-rss",
        name="Washington Post Business",
        category=CATEGORY_US_ECONOMY,
        base_url="https://www.washingtonpost.com",
        feed_url="https://feeds.washingtonpost.com/rss/business",
        trust_level=92,
        hub=HUB_US,
        section="economy",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="cnn-us-rss",
        name="CNN US",
        category=CATEGORY_US_POLITICS,
        base_url="https://www.cnn.com",
        feed_url="http://rss.cnn.com/rss/edition_us.rss",
        trust_level=88,
        hub=HUB_US,
        section="politics",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="cnn-world-rss",
        name="CNN World",
        category=CATEGORY_US_WORLD,
        base_url="https://www.cnn.com",
        feed_url="http://rss.cnn.com/rss/edition_world.rss",
        trust_level=88,
        hub=HUB_US,
        section="world",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="cnn-money-rss",
        name="CNN Markets",
        category=CATEGORY_US_MARKETS,
        base_url="https://www.cnn.com",
        feed_url="http://rss.cnn.com/rss/money_latest.rss",
        trust_level=88,
        hub=HUB_US,
        section="markets",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="cnn-technology-rss",
        name="CNN Technology",
        category=CATEGORY_US_TECHNOLOGY,
        base_url="https://www.cnn.com",
        feed_url="http://rss.cnn.com/rss/edition_technology.rss",
        trust_level=88,
        hub=HUB_US,
        section="technology",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="fox-us-rss",
        name="Fox News US",
        category=CATEGORY_US_POLITICS,
        base_url="https://www.foxnews.com",
        feed_url="https://moxie.foxnews.com/google-publisher/us.xml",
        trust_level=84,
        hub=HUB_US,
        section="politics",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="fox-world-rss",
        name="Fox News World",
        category=CATEGORY_US_WORLD,
        base_url="https://www.foxnews.com",
        feed_url="https://moxie.foxnews.com/google-publisher/world.xml",
        trust_level=84,
        hub=HUB_US,
        section="world",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="fox-politics-rss",
        name="Fox News Politics",
        category=CATEGORY_US_POLITICS,
        base_url="https://www.foxnews.com",
        feed_url="https://moxie.foxnews.com/google-publisher/politics.xml",
        trust_level=84,
        hub=HUB_US,
        section="politics",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="abc-us-rss",
        name="ABC News US",
        category=CATEGORY_US_POLITICS,
        base_url="https://abcnews.go.com",
        feed_url="https://feeds.abcnews.com/abcnews/usheadlines",
        trust_level=87,
        hub=HUB_US,
        section="politics",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="abc-world-rss",
        name="ABC News World",
        category=CATEGORY_US_WORLD,
        base_url="https://abcnews.go.com",
        feed_url="https://feeds.abcnews.com/abcnews/worldnewsheadlines",
        trust_level=87,
        hub=HUB_US,
        section="world",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="abc-politics-rss",
        name="ABC News Politics",
        category=CATEGORY_US_POLITICS,
        base_url="https://abcnews.go.com",
        feed_url="https://feeds.abcnews.com/abcnews/politicsheadlines",
        trust_level=87,
        hub=HUB_US,
        section="politics",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="abc-money-rss",
        name="ABC News Money",
        category=CATEGORY_US_ECONOMY,
        base_url="https://abcnews.go.com",
        feed_url="https://feeds.abcnews.com/abcnews/moneyheadlines",
        trust_level=87,
        hub=HUB_US,
        section="economy",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="abc-technology-rss",
        name="ABC News Technology",
        category=CATEGORY_US_TECHNOLOGY,
        base_url="https://abcnews.go.com",
        feed_url="https://feeds.abcnews.com/abcnews/technologyheadlines",
        trust_level=87,
        hub=HUB_US,
        section="technology",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="cbs-us-rss",
        name="CBS News US",
        category=CATEGORY_US_POLITICS,
        base_url="https://www.cbsnews.com",
        feed_url="https://www.cbsnews.com/latest/rss/us",
        trust_level=87,
        hub=HUB_US,
        section="politics",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="cbs-world-rss",
        name="CBS News World",
        category=CATEGORY_US_WORLD,
        base_url="https://www.cbsnews.com",
        feed_url="https://www.cbsnews.com/latest/rss/world",
        trust_level=87,
        hub=HUB_US,
        section="world",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="cbs-politics-rss",
        name="CBS News Politics",
        category=CATEGORY_US_POLITICS,
        base_url="https://www.cbsnews.com",
        feed_url="https://www.cbsnews.com/latest/rss/politics",
        trust_level=87,
        hub=HUB_US,
        section="politics",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="cbs-moneywatch-rss",
        name="CBS MoneyWatch",
        category=CATEGORY_US_MARKETS,
        base_url="https://www.cbsnews.com",
        feed_url="https://www.cbsnews.com/latest/rss/moneywatch",
        trust_level=87,
        hub=HUB_US,
        section="markets",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="cbs-technology-rss",
        name="CBS News Technology",
        category=CATEGORY_US_TECHNOLOGY,
        base_url="https://www.cbsnews.com",
        feed_url="https://www.cbsnews.com/latest/rss/technology",
        trust_level=87,
        hub=HUB_US,
        section="technology",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="msnbc-feed",
        name="MSNBC Feed",
        category=None,
        base_url="https://www.msnbc.com",
        feed_url="https://www.ms.now/feed",
        trust_level=82,
        hub=HUB_US,
        section="general",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="axios-feed",
        name="Axios Feed",
        category=None,
        base_url="https://www.axios.com",
        feed_url="https://api.axios.com/feed/",
        trust_level=85,
        hub=HUB_US,
        section="general",
        publisher_group="internet",
    ),
    _rss_source(
        source_key="thehill-feed",
        name="The Hill Feed",
        category=None,
        base_url="https://thehill.com",
        feed_url="https://thehill.com/feed/",
        trust_level=80,
        hub=HUB_US,
        section="general",
        publisher_group="internet",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="bloomberg-politics-rss",
        name="Bloomberg Politics",
        category=CATEGORY_US_POLITICS,
        base_url="https://www.bloomberg.com",
        feed_url="https://feeds.bloomberg.com/politics/news.rss",
        trust_level=92,
        hub=HUB_US,
        section="politics",
        publisher_group="business",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="bloomberg-markets-rss",
        name="Bloomberg Markets",
        category=CATEGORY_US_MARKETS,
        base_url="https://www.bloomberg.com",
        feed_url="https://feeds.bloomberg.com/markets/news.rss",
        trust_level=92,
        hub=HUB_US,
        section="markets",
        publisher_group="business",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="bloomberg-tech-rss",
        name="Bloomberg Technology",
        category=CATEGORY_US_TECHNOLOGY,
        base_url="https://www.bloomberg.com",
        feed_url="https://feeds.bloomberg.com/technology/news.rss",
        trust_level=92,
        hub=HUB_US,
        section="technology",
        publisher_group="business",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="huffpost-politics-rss",
        name="HuffPost Politics",
        category=CATEGORY_US_POLITICS,
        base_url="https://www.huffpost.com",
        feed_url="https://www.huffpost.com/section/politics/feed",
        trust_level=76,
        hub=HUB_US,
        section="politics",
        publisher_group="internet",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="nypost-feed",
        name="New York Post Feed",
        category=None,
        base_url="https://nypost.com",
        feed_url="https://nypost.com/feed/",
        trust_level=70,
        hub=HUB_US,
        section="general",
        publisher_group="newspaper",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="npr-top-rss",
        name="NPR Top Stories",
        category=None,
        base_url="https://www.npr.org",
        feed_url="https://feeds.npr.org/1001/rss.xml",
        trust_level=90,
        hub=HUB_US,
        section="general",
        publisher_group="public-media",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="npr-world-rss",
        name="NPR World",
        category=CATEGORY_US_WORLD,
        base_url="https://www.npr.org",
        feed_url="https://feeds.npr.org/1004/rss.xml",
        trust_level=90,
        hub=HUB_US,
        section="world",
        publisher_group="public-media",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="npr-business-rss",
        name="NPR Business",
        category=CATEGORY_US_ECONOMY,
        base_url="https://www.npr.org",
        feed_url="https://feeds.npr.org/1006/rss.xml",
        trust_level=90,
        hub=HUB_US,
        section="economy",
        publisher_group="public-media",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="npr-politics-rss",
        name="NPR Politics",
        category=CATEGORY_US_POLITICS,
        base_url="https://www.npr.org",
        feed_url="https://feeds.npr.org/1014/rss.xml",
        trust_level=90,
        hub=HUB_US,
        section="politics",
        publisher_group="public-media",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="npr-tech-rss",
        name="NPR Technology",
        category=CATEGORY_US_TECHNOLOGY,
        base_url="https://www.npr.org",
        feed_url="https://feeds.npr.org/1019/rss.xml",
        trust_level=90,
        hub=HUB_US,
        section="technology",
        publisher_group="public-media",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="cnbc-top-rss",
        name="CNBC Top News",
        category=None,
        base_url="https://www.cnbc.com",
        feed_url="https://www.cnbc.com/id/100003114/device/rss/rss.html",
        trust_level=84,
        hub=HUB_US,
        section="general",
        publisher_group="broadcast",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="cnbc-world-rss",
        name="CNBC World",
        category=CATEGORY_US_WORLD,
        base_url="https://www.cnbc.com",
        feed_url="https://www.cnbc.com/id/100727362/device/rss/rss.html",
        trust_level=84,
        hub=HUB_US,
        section="world",
        publisher_group="broadcast",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="cnbc-tech-rss",
        name="CNBC Technology",
        category=CATEGORY_US_TECHNOLOGY,
        base_url="https://www.cnbc.com",
        feed_url="https://www.cnbc.com/id/19854910/device/rss/rss.html",
        trust_level=84,
        hub=HUB_US,
        section="technology",
        publisher_group="broadcast",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="atlantic-feed",
        name="The Atlantic Feed",
        category=None,
        base_url="https://www.theatlantic.com",
        feed_url="https://www.theatlantic.com/feed/all/",
        trust_level=82,
        hub=HUB_US,
        section="general",
        publisher_group="magazine",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="newsweek-feed",
        name="Newsweek Feed",
        category=None,
        base_url="https://www.newsweek.com",
        feed_url="https://www.newsweek.com/rss.xml",
        trust_level=78,
        hub=HUB_US,
        section="general",
        publisher_group="magazine",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="pbs-politics-rss",
        name="PBS NewsHour Politics",
        category=CATEGORY_US_POLITICS,
        base_url="https://www.pbs.org",
        feed_url="https://www.pbs.org/newshour/feeds/rss/politics",
        trust_level=88,
        hub=HUB_US,
        section="politics",
        publisher_group="public-media",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="pbs-world-rss",
        name="PBS NewsHour World",
        category=CATEGORY_US_WORLD,
        base_url="https://www.pbs.org",
        feed_url="https://www.pbs.org/newshour/feeds/rss/world",
        trust_level=88,
        hub=HUB_US,
        section="world",
        publisher_group="public-media",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="pbs-economy-rss",
        name="PBS NewsHour Economy",
        category=CATEGORY_US_ECONOMY,
        base_url="https://www.pbs.org",
        feed_url="https://www.pbs.org/newshour/feeds/rss/economy",
        trust_level=88,
        hub=HUB_US,
        section="economy",
        publisher_group="public-media",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="pbs-science-rss",
        name="PBS NewsHour Science",
        category=CATEGORY_US_TECHNOLOGY,
        base_url="https://www.pbs.org",
        feed_url="https://www.pbs.org/newshour/feeds/rss/science",
        trust_level=88,
        hub=HUB_US,
        section="technology",
        publisher_group="public-media",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="businessinsider-feed",
        name="Business Insider Feed",
        category=None,
        base_url="https://www.businessinsider.com",
        feed_url="https://www.businessinsider.com/rss",
        trust_level=77,
        hub=HUB_US,
        section="general",
        publisher_group="internet",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="propublica-feed",
        name="ProPublica Feed",
        category=None,
        base_url="https://www.propublica.org",
        feed_url="https://www.propublica.org/feeds/propublica/main",
        trust_level=89,
        hub=HUB_US,
        section="general",
        publisher_group="nonprofit",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="time-feed",
        name="Time Feed",
        category=None,
        base_url="https://time.com",
        feed_url="https://time.com/feed/",
        trust_level=80,
        hub=HUB_US,
        section="general",
        publisher_group="magazine",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="yahoo-news-rss",
        name="Yahoo News RSS",
        category=None,
        base_url="https://news.yahoo.com",
        feed_url="https://news.yahoo.com/rss/",
        trust_level=55,
        hub=HUB_US,
        section="general",
        publisher_group="internet",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="guardian-us-rss",
        name="The Guardian US",
        category=None,
        base_url="https://www.theguardian.com",
        feed_url="https://www.theguardian.com/us/rss",
        trust_level=86,
        hub=HUB_US,
        section="general",
        publisher_group="newspaper",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="guardian-tech-rss",
        name="The Guardian US Technology",
        category=CATEGORY_US_TECHNOLOGY,
        base_url="https://www.theguardian.com",
        feed_url="https://www.theguardian.com/us/technology/rss",
        trust_level=86,
        hub=HUB_US,
        section="technology",
        publisher_group="newspaper",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="vox-feed",
        name="Vox Feed",
        category=None,
        base_url="https://www.vox.com",
        feed_url="https://www.vox.com/rss/index.xml",
        trust_level=78,
        hub=HUB_US,
        section="general",
        publisher_group="internet",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="slate-politics-rss",
        name="Slate News and Politics",
        category=CATEGORY_US_POLITICS,
        base_url="https://slate.com",
        feed_url="https://slate.com/feeds/news-and-politics.rss",
        trust_level=74,
        hub=HUB_US,
        section="politics",
        publisher_group="magazine",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="salon-feed",
        name="Salon Feed",
        category=None,
        base_url="https://www.salon.com",
        feed_url="https://www.salon.com/feed",
        trust_level=70,
        hub=HUB_US,
        section="general",
        publisher_group="internet",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="washingtonexaminer-feed",
        name="Washington Examiner Feed",
        category=None,
        base_url="https://www.washingtonexaminer.com",
        feed_url="https://www.washingtonexaminer.com/feed",
        trust_level=69,
        hub=HUB_US,
        section="general",
        publisher_group="newspaper",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="nationalreview-feed",
        name="National Review Feed",
        category=None,
        base_url="https://www.nationalreview.com",
        feed_url="https://www.nationalreview.com/feed/",
        trust_level=72,
        hub=HUB_US,
        section="general",
        publisher_group="magazine",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="federalist-feed",
        name="The Federalist Feed",
        category=None,
        base_url="https://thefederalist.com",
        feed_url="https://thefederalist.com/feed/",
        trust_level=68,
        hub=HUB_US,
        section="general",
        publisher_group="internet",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="motherjones-feed",
        name="Mother Jones Feed",
        category=None,
        base_url="https://www.motherjones.com",
        feed_url="https://www.motherjones.com/feed/",
        trust_level=78,
        hub=HUB_US,
        section="general",
        publisher_group="magazine",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="wired-rss",
        name="Wired RSS",
        category=CATEGORY_US_TECHNOLOGY,
        base_url="https://www.wired.com",
        feed_url="https://www.wired.com/feed/rss",
        trust_level=86,
        hub=HUB_US,
        section="technology",
        publisher_group="magazine",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="semafor-feed",
        name="Semafor Feed",
        category=None,
        base_url="https://www.semafor.com",
        feed_url="https://www.semafor.com/rss.xml",
        trust_level=80,
        hub=HUB_US,
        section="general",
        publisher_group="internet",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="verge-rss",
        name="The Verge RSS",
        category=CATEGORY_US_TECHNOLOGY,
        base_url="https://www.theverge.com",
        feed_url="https://www.theverge.com/rss/index.xml",
        trust_level=84,
        hub=HUB_US,
        section="technology",
        publisher_group="internet",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="fortune-feed",
        name="Fortune Feed",
        category=None,
        base_url="https://fortune.com",
        feed_url="https://fortune.com/feed/",
        trust_level=81,
        hub=HUB_US,
        section="general",
        publisher_group="business",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="forbes-business-rss",
        name="Forbes Business",
        category=CATEGORY_US_ECONOMY,
        base_url="https://www.forbes.com",
        feed_url="https://www.forbes.com/business/feed2/",
        trust_level=82,
        hub=HUB_US,
        section="economy",
        publisher_group="business",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="forbes-innovation-rss",
        name="Forbes Innovation",
        category=CATEGORY_US_TECHNOLOGY,
        base_url="https://www.forbes.com",
        feed_url="https://www.forbes.com/innovation/feed2/",
        trust_level=82,
        hub=HUB_US,
        section="technology",
        publisher_group="business",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="latimes-politics-rss",
        name="Los Angeles Times Politics",
        category=CATEGORY_US_POLITICS,
        base_url="https://www.latimes.com",
        feed_url="https://www.latimes.com/politics/rss2.0.xml",
        trust_level=84,
        hub=HUB_US,
        section="politics",
        publisher_group="newspaper",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="latimes-business-rss",
        name="Los Angeles Times Business",
        category=CATEGORY_US_ECONOMY,
        base_url="https://www.latimes.com",
        feed_url="https://www.latimes.com/business/rss2.0.xml",
        trust_level=84,
        hub=HUB_US,
        section="economy",
        publisher_group="newspaper",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="latimes-world-rss",
        name="Los Angeles Times World",
        category=CATEGORY_US_WORLD,
        base_url="https://www.latimes.com",
        feed_url="https://www.latimes.com/world-nation/rss2.0.xml",
        trust_level=84,
        hub=HUB_US,
        section="world",
        publisher_group="newspaper",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="latimes-tech-rss",
        name="Los Angeles Times Technology",
        category=CATEGORY_US_TECHNOLOGY,
        base_url="https://www.latimes.com",
        feed_url="https://www.latimes.com/business/technology/rss2.0.xml",
        trust_level=84,
        hub=HUB_US,
        section="technology",
        publisher_group="newspaper",
        poll_interval_sec=600,
    ),
    _rss_source(
        source_key="breitbart-feed",
        name="Breitbart Feed",
        category=None,
        base_url="https://www.breitbart.com",
        feed_url="https://www.breitbart.com/feed/",
        trust_level=66,
        hub=HUB_US,
        section="general",
        publisher_group="internet",
        poll_interval_sec=600,
    ),
    _html_source(
        source_key="ap-politics-discovery",
        name="Associated Press Politics",
        category=CATEGORY_US_POLITICS,
        base_url="https://apnews.com",
        page_url="https://apnews.com/politics",
        allowed_domains=["apnews.com", "www.apnews.com"],
        article_prefixes=["/article/", "/hub/"],
        trust_level=90,
        hub=HUB_US,
        section="politics",
        publisher_group="agency",
    ),
    _html_source(
        source_key="ap-business-discovery",
        name="Associated Press Business",
        category=CATEGORY_US_ECONOMY,
        base_url="https://apnews.com",
        page_url="https://apnews.com/business",
        allowed_domains=["apnews.com", "www.apnews.com"],
        article_prefixes=["/article/", "/hub/"],
        trust_level=90,
        hub=HUB_US,
        section="economy",
        publisher_group="agency",
    ),
    _html_source(
        source_key="ap-technology-discovery",
        name="Associated Press Technology",
        category=CATEGORY_US_TECHNOLOGY,
        base_url="https://apnews.com",
        page_url="https://apnews.com/technology",
        allowed_domains=["apnews.com", "www.apnews.com"],
        article_prefixes=["/article/", "/hub/"],
        trust_level=90,
        hub=HUB_US,
        section="technology",
        publisher_group="agency",
    ),
    _html_source(
        source_key="nbc-politics-discovery",
        name="NBC News Politics",
        category=CATEGORY_US_POLITICS,
        base_url="https://www.nbcnews.com",
        page_url="https://www.nbcnews.com/politics",
        allowed_domains=["www.nbcnews.com", "nbcnews.com"],
        article_prefixes=["/politics/", "/news/", "/business/"],
        trust_level=84,
        hub=HUB_US,
        section="politics",
        publisher_group="broadcast",
    ),
    _html_source(
        source_key="nbc-business-discovery",
        name="NBC News Business",
        category=CATEGORY_US_ECONOMY,
        base_url="https://www.nbcnews.com",
        page_url="https://www.nbcnews.com/business",
        allowed_domains=["www.nbcnews.com", "nbcnews.com"],
        article_prefixes=["/business/", "/news/"],
        trust_level=84,
        hub=HUB_US,
        section="economy",
        publisher_group="broadcast",
    ),
    _html_source(
        source_key="nbc-tech-discovery",
        name="NBC News Tech Media",
        category=CATEGORY_US_TECHNOLOGY,
        base_url="https://www.nbcnews.com",
        page_url="https://www.nbcnews.com/tech-media",
        allowed_domains=["www.nbcnews.com", "nbcnews.com"],
        article_prefixes=["/tech-media/", "/tech/", "/news/"],
        trust_level=84,
        hub=HUB_US,
        section="technology",
        publisher_group="broadcast",
    ),
    _html_source(
        source_key="usatoday-news-discovery",
        name="USA Today News",
        category=None,
        base_url="https://www.usatoday.com",
        page_url="https://www.usatoday.com/news/",
        allowed_domains=["www.usatoday.com", "usatoday.com"],
        article_prefixes=["/story/"],
        trust_level=82,
        hub=HUB_US,
        section="general",
        publisher_group="newspaper",
    ),
    _html_source(
        source_key="usatoday-money-discovery",
        name="USA Today Money",
        category=CATEGORY_US_MARKETS,
        base_url="https://www.usatoday.com",
        page_url="https://www.usatoday.com/money/",
        allowed_domains=["www.usatoday.com", "usatoday.com"],
        article_prefixes=["/story/money/", "/story/news/"],
        trust_level=82,
        hub=HUB_US,
        section="markets",
        publisher_group="newspaper",
    ),
    _html_source(
        source_key="usatoday-tech-discovery",
        name="USA Today Tech",
        category=CATEGORY_US_TECHNOLOGY,
        base_url="https://www.usatoday.com",
        page_url="https://www.usatoday.com/tech/",
        allowed_domains=["www.usatoday.com", "usatoday.com"],
        article_prefixes=["/story/tech/", "/story/news/"],
        trust_level=82,
        hub=HUB_US,
        section="technology",
        publisher_group="newspaper",
    ),
    _html_source(
        source_key="naver-kr-society",
        name="NAVER News Search",
        category=CATEGORY_KR_SOCIETY,
        base_url="https://news.naver.com",
        page_url="https://news.naver.com/section/102",
        allowed_domains=["n.news.naver.com"],
        article_prefixes=["/mnews/article/"],
        trust_level=70,
        hub=HUB_KR,
        section="society",
        publisher_group="search",
        poll_interval_sec=600,
        discovery_only=True,
    ),
    _rss_source(
        source_key="sbs-politics-rss",
        name="SBS Politics",
        category=CATEGORY_KR_POLITICS,
        base_url="https://news.sbs.co.kr",
        feed_url="https://news.sbs.co.kr/news/SectionRssFeed.do?sectionId=01&plink=RSSREADER",
        trust_level=82,
        hub=HUB_KR,
        section="politics",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="sbs-economy-rss",
        name="SBS Economy",
        category=CATEGORY_KR_ECONOMY,
        base_url="https://news.sbs.co.kr",
        feed_url="https://news.sbs.co.kr/news/SectionRssFeed.do?sectionId=02&plink=RSSREADER",
        trust_level=82,
        hub=HUB_KR,
        section="economy",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="sbs-society-rss",
        name="SBS Society",
        category=CATEGORY_KR_SOCIETY,
        base_url="https://news.sbs.co.kr",
        feed_url="https://news.sbs.co.kr/news/SectionRssFeed.do?sectionId=03&plink=RSSREADER",
        trust_level=82,
        hub=HUB_KR,
        section="society",
        publisher_group="broadcast",
    ),
    _rss_source(
        source_key="khan-politics-rss",
        name="Kyunghyang Politics",
        category=CATEGORY_KR_POLITICS,
        base_url="https://www.khan.co.kr",
        feed_url="https://www.khan.co.kr/rss/rssdata/politic_news.xml",
        trust_level=86,
        hub=HUB_KR,
        section="politics",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="khan-economy-rss",
        name="Kyunghyang Economy",
        category=CATEGORY_KR_ECONOMY,
        base_url="https://www.khan.co.kr",
        feed_url="https://www.khan.co.kr/rss/rssdata/economy_news.xml",
        trust_level=86,
        hub=HUB_KR,
        section="economy",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="khan-society-rss",
        name="Kyunghyang Society",
        category=CATEGORY_KR_SOCIETY,
        base_url="https://www.khan.co.kr",
        feed_url="https://www.khan.co.kr/rss/rssdata/society_news.xml",
        trust_level=86,
        hub=HUB_KR,
        section="society",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="khan-local-rss",
        name="Kyunghyang Local",
        category=CATEGORY_KR_LOCAL,
        base_url="https://www.khan.co.kr",
        feed_url="https://www.khan.co.kr/rss/rssdata/local_news.xml",
        trust_level=86,
        hub=HUB_KR,
        section="local",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="khan-culture-rss",
        name="Kyunghyang Culture",
        category=CATEGORY_KR_CULTURE,
        base_url="https://www.khan.co.kr",
        feed_url="https://www.khan.co.kr/rss/rssdata/culture_news.xml",
        trust_level=86,
        hub=HUB_KR,
        section="culture",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="khan-sports-rss",
        name="Kyunghyang Sports",
        category=CATEGORY_KR_SPORTS,
        base_url="https://www.khan.co.kr",
        feed_url="http://www.khan.co.kr/rss/rssdata/kh_sports.xml",
        trust_level=86,
        hub=HUB_KR,
        section="sports",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="donga-politics-rss",
        name="DongA Politics",
        category=CATEGORY_KR_POLITICS,
        base_url="https://www.donga.com",
        feed_url="https://rss.donga.com/politics.xml",
        trust_level=88,
        hub=HUB_KR,
        section="politics",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="donga-economy-rss",
        name="DongA Economy",
        category=CATEGORY_KR_ECONOMY,
        base_url="https://www.donga.com",
        feed_url="https://rss.donga.com/economy.xml",
        trust_level=88,
        hub=HUB_KR,
        section="economy",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="donga-society-rss",
        name="DongA Society",
        category=CATEGORY_KR_SOCIETY,
        base_url="https://www.donga.com",
        feed_url="https://rss.donga.com/national.xml",
        trust_level=88,
        hub=HUB_KR,
        section="society",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="donga-culture-rss",
        name="DongA Culture",
        category=CATEGORY_KR_CULTURE,
        base_url="https://www.donga.com",
        feed_url="https://rss.donga.com/culture.xml",
        trust_level=88,
        hub=HUB_KR,
        section="culture",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="donga-sports-rss",
        name="DongA Sports",
        category=CATEGORY_KR_SPORTS,
        base_url="https://www.donga.com",
        feed_url="https://rss.donga.com/sports.xml",
        trust_level=88,
        hub=HUB_KR,
        section="sports",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="mk-politics-rss",
        name="Maeil Business Politics",
        category=CATEGORY_KR_POLITICS,
        base_url="https://www.mk.co.kr",
        feed_url="https://www.mk.co.kr/rss/30200030/",
        trust_level=89,
        hub=HUB_KR,
        section="politics",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="mk-economy-rss",
        name="Maeil Business Economy",
        category=CATEGORY_KR_ECONOMY,
        base_url="https://www.mk.co.kr",
        feed_url="https://www.mk.co.kr/rss/30100041/",
        trust_level=89,
        hub=HUB_KR,
        section="economy",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="mk-society-rss",
        name="Maeil Business Society",
        category=CATEGORY_KR_SOCIETY,
        base_url="https://www.mk.co.kr",
        feed_url="https://www.mk.co.kr/rss/50400012/",
        trust_level=89,
        hub=HUB_KR,
        section="society",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="mk-culture-rss",
        name="Maeil Business Culture",
        category=CATEGORY_KR_CULTURE,
        base_url="https://www.mk.co.kr",
        feed_url="https://www.mk.co.kr/rss/30000023/",
        trust_level=89,
        hub=HUB_KR,
        section="culture",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="mk-sports-rss",
        name="Maeil Business Sports",
        category=CATEGORY_KR_SPORTS,
        base_url="https://www.mk.co.kr",
        feed_url="https://www.mk.co.kr/rss/71000001/",
        trust_level=89,
        hub=HUB_KR,
        section="sports",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="asiae-politics-rss",
        name="Asiae Politics",
        category=CATEGORY_KR_POLITICS,
        base_url="https://www.asiae.co.kr",
        feed_url="https://www.asiae.co.kr/rss/politics.htm",
        trust_level=84,
        hub=HUB_KR,
        section="politics",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="asiae-economy-rss",
        name="Asiae Economy",
        category=CATEGORY_KR_ECONOMY,
        base_url="https://www.asiae.co.kr",
        feed_url="https://www.asiae.co.kr/rss/economy.htm",
        trust_level=84,
        hub=HUB_KR,
        section="economy",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="asiae-society-rss",
        name="Asiae Society",
        category=CATEGORY_KR_SOCIETY,
        base_url="https://www.asiae.co.kr",
        feed_url="https://www.asiae.co.kr/rss/society.htm",
        trust_level=84,
        hub=HUB_KR,
        section="society",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="asiae-culture-rss",
        name="Asiae Life",
        category=CATEGORY_KR_CULTURE,
        base_url="https://www.asiae.co.kr",
        feed_url="https://www.asiae.co.kr/rss/life.htm",
        trust_level=84,
        hub=HUB_KR,
        section="culture",
        publisher_group="newspaper",
    ),
    _rss_source(
        source_key="etoday-economy-rss",
        name="eToday Economy",
        category=CATEGORY_KR_ECONOMY,
        base_url="https://www.etoday.co.kr",
        feed_url="https://rss.etoday.co.kr/eto/etoday_news_all.xml",
        trust_level=79,
        hub=HUB_KR,
        section="economy",
        publisher_group="internet",
    ),
    _html_source(
        source_key="ytn-politics-discovery",
        name="YTN Politics",
        category=CATEGORY_KR_POLITICS,
        base_url="https://www.ytn.co.kr",
        page_url="https://www.ytn.co.kr/news/list.php?mcd=0101",
        allowed_domains=["www.ytn.co.kr", "ytn.co.kr"],
        article_prefixes=["/_ln/0101_", "/_ln/0101/"],
        trust_level=82,
        hub=HUB_KR,
        section="politics",
        publisher_group="broadcast",
    ),
    _html_source(
        source_key="ytn-economy-discovery",
        name="YTN Economy",
        category=CATEGORY_KR_ECONOMY,
        base_url="https://www.ytn.co.kr",
        page_url="https://www.ytn.co.kr/news/list.php?mcd=0102",
        allowed_domains=["www.ytn.co.kr", "ytn.co.kr"],
        article_prefixes=["/_ln/0102_", "/_ln/0102/"],
        trust_level=82,
        hub=HUB_KR,
        section="economy",
        publisher_group="broadcast",
    ),
    _html_source(
        source_key="ytn-society-discovery",
        name="YTN Society",
        category=CATEGORY_KR_SOCIETY,
        base_url="https://www.ytn.co.kr",
        page_url="https://www.ytn.co.kr/news/list.php?mcd=0103",
        allowed_domains=["www.ytn.co.kr", "ytn.co.kr"],
        article_prefixes=["/_ln/0103_", "/_ln/0103/"],
        trust_level=82,
        hub=HUB_KR,
        section="society",
        publisher_group="broadcast",
    ),
    _html_source(
        source_key="ytn-culture-discovery",
        name="YTN Culture",
        category=CATEGORY_KR_CULTURE,
        base_url="https://www.ytn.co.kr",
        page_url="https://www.ytn.co.kr/news/list.php?mcd=0106",
        allowed_domains=["www.ytn.co.kr", "ytn.co.kr"],
        article_prefixes=["/_ln/0106_", "/_ln/0106/"],
        trust_level=82,
        hub=HUB_KR,
        section="culture",
        publisher_group="broadcast",
    ),
    _html_source(
        source_key="ytn-sports-discovery",
        name="YTN Sports",
        category=CATEGORY_KR_SPORTS,
        base_url="https://www.ytn.co.kr",
        page_url="https://www.ytn.co.kr/news/list.php?mcd=0107",
        allowed_domains=["www.ytn.co.kr", "ytn.co.kr"],
        article_prefixes=["/_ln/0107_", "/_ln/0107/"],
        trust_level=82,
        hub=HUB_KR,
        section="sports",
        publisher_group="broadcast",
    ),
    _html_source(
        source_key="hani-economy-discovery",
        name="Hankyoreh Economy",
        category=CATEGORY_KR_ECONOMY,
        base_url="https://www.hani.co.kr",
        page_url="https://www.hani.co.kr/arti/economy/",
        allowed_domains=["www.hani.co.kr", "hani.co.kr"],
        article_prefixes=["/arti/economy/"],
        trust_level=83,
        hub=HUB_KR,
        section="economy",
        publisher_group="newspaper",
    ),
    _html_source(
        source_key="hani-society-discovery",
        name="Hankyoreh Society",
        category=CATEGORY_KR_SOCIETY,
        base_url="https://www.hani.co.kr",
        page_url="https://www.hani.co.kr/arti/society/",
        allowed_domains=["www.hani.co.kr", "hani.co.kr"],
        article_prefixes=["/arti/society/"],
        trust_level=83,
        hub=HUB_KR,
        section="society",
        publisher_group="newspaper",
    ),
    _html_source(
        source_key="hani-culture-discovery",
        name="Hankyoreh Culture",
        category=CATEGORY_KR_CULTURE,
        base_url="https://www.hani.co.kr",
        page_url="https://www.hani.co.kr/arti/culture/",
        allowed_domains=["www.hani.co.kr", "hani.co.kr"],
        article_prefixes=["/arti/culture/"],
        trust_level=83,
        hub=HUB_KR,
        section="culture",
        publisher_group="newspaper",
    ),
    _html_source(
        source_key="hani-local-discovery",
        name="Hankyoreh Local",
        category=CATEGORY_KR_LOCAL,
        base_url="https://www.hani.co.kr",
        page_url="https://www.hani.co.kr/arti/area/",
        allowed_domains=["www.hani.co.kr", "hani.co.kr"],
        article_prefixes=["/arti/area/"],
        trust_level=83,
        hub=HUB_KR,
        section="local",
        publisher_group="newspaper",
    ),
    _html_source(
        source_key="chosun-politics-discovery",
        name="Chosun Politics",
        category=CATEGORY_KR_POLITICS,
        base_url="https://www.chosun.com",
        page_url="https://www.chosun.com/politics/politics_general/",
        allowed_domains=["www.chosun.com", "chosun.com"],
        article_prefixes=["/politics/"],
        trust_level=84,
        hub=HUB_KR,
        section="politics",
        publisher_group="newspaper",
    ),
    _html_source(
        source_key="chosun-economy-discovery",
        name="Chosun Economy",
        category=CATEGORY_KR_ECONOMY,
        base_url="https://www.chosun.com",
        page_url="https://www.chosun.com/economy/",
        allowed_domains=["www.chosun.com", "chosun.com"],
        article_prefixes=["/economy/"],
        trust_level=84,
        hub=HUB_KR,
        section="economy",
        publisher_group="newspaper",
    ),
    _html_source(
        source_key="chosun-culture-discovery",
        name="Chosun Culture",
        category=CATEGORY_KR_CULTURE,
        base_url="https://www.chosun.com",
        page_url="https://www.chosun.com/culture-life/",
        allowed_domains=["www.chosun.com", "chosun.com"],
        article_prefixes=["/culture-life/", "/entertainments/"],
        trust_level=84,
        hub=HUB_KR,
        section="culture",
        publisher_group="newspaper",
    ),
    _html_source(
        source_key="yahoo-finance-discovery",
        name="Yahoo Finance Discovery",
        category=CATEGORY_US_MARKETS,
        base_url="https://finance.yahoo.com",
        page_url="https://finance.yahoo.com/",
        allowed_domains=["finance.yahoo.com"],
        article_prefixes=["/news/", "/video/"],
        trust_level=40,
        hub=HUB_US,
        section="markets",
        publisher_group="internet",
        discovery_only=True,
        static_enabled=False,
    ),
    _html_source(
        source_key="financialjuice-discovery",
        name="FinancialJuice Discovery",
        category=CATEGORY_US_MARKETS,
        base_url="https://www.financialjuice.com",
        page_url="https://www.financialjuice.com/home",
        allowed_domains=["www.financialjuice.com", "financialjuice.com"],
        article_prefixes=["/home", "/news", "/article"],
        trust_level=35,
        hub=HUB_US,
        section="markets",
        publisher_group="internet",
        discovery_only=True,
        static_enabled=False,
    ),
    SourceDefinition(
        source_key="telegram-dada-news2",
        name="Telegram @dada_news2",
        adapter_type="telegram_channel",
        category=None,
        poll_interval_sec=180,
        base_url="https://t.me/dada_news2",
        trust_level=55,
        config={
            "channel": "dada_news2",
            **_meta(
                hub=HUB_GLOBAL,
                section="general",
                publisher_group="social",
            ),
        },
    ),
    SourceDefinition(
        source_key="telegram-news-kor",
        name="Telegram @news_kor",
        adapter_type="telegram_channel",
        category=None,
        poll_interval_sec=180,
        base_url="https://t.me/news_kor",
        trust_level=55,
        config={
            "channel": "news_kor",
            **_meta(
                hub=HUB_KR,
                section="general",
                publisher_group="social",
            ),
        },
    ),
    SourceDefinition(
        source_key="telegram-claw-summary",
        name="Telegram @clawnewssummary",
        adapter_type="telegram_channel",
        category=None,
        poll_interval_sec=180,
        base_url="https://t.me/clawnewssummary",
        trust_level=55,
        config={
            "channel": "clawnewssummary",
            **_meta(
                hub=HUB_GLOBAL,
                section="general",
                publisher_group="social",
            ),
        },
    ),
]


def _normalize_telegram_channel(value: str) -> str | None:
    normalized = value.strip()
    if not normalized:
        return None

    if normalized.startswith(("http://", "https://")):
        parsed = urlsplit(normalized)
        if parsed.netloc.lower() not in {
            "t.me",
            "www.t.me",
            "telegram.me",
            "www.telegram.me",
        }:
            return None
        normalized = parsed.path.strip("/")

    normalized = normalized.lstrip("@").strip("/")
    if not normalized or normalized.startswith("+"):
        return None
    normalized = normalized.split("/", 1)[0]
    if not _TELEGRAM_CHANNEL_PATTERN.fullmatch(normalized):
        return None
    return normalized


def _iter_env_telegram_channels() -> list[str]:
    channels: list[str] = []
    seen: set[str] = set()
    for key in _ENV_TELEGRAM_CHANNEL_KEYS:
        raw_value = os.getenv(key, "")
        if not raw_value.strip():
            continue
        for part in _ENV_CHANNEL_SPLIT_PATTERN.split(raw_value):
            channel = _normalize_telegram_channel(part)
            if channel is None:
                continue
            normalized_key = channel.lower()
            if normalized_key in seen:
                continue
            seen.add(normalized_key)
            channels.append(channel)
    return channels


def _build_env_telegram_source(channel: str) -> SourceDefinition:
    slug = channel.lower().replace("_", "-")
    return SourceDefinition(
        source_key=f"telegram-env-{slug}",
        name=f"Telegram @{channel}",
        adapter_type="telegram_channel",
        category=None,
        poll_interval_sec=180,
        base_url=f"https://t.me/{channel}",
        trust_level=55,
        config={
            "channel": channel,
            **_meta(
                hub=HUB_GLOBAL,
                section="general",
                publisher_group="social",
            ),
        },
    )


def get_source_definitions() -> list[SourceDefinition]:
    definitions = list(BASE_SOURCE_DEFINITIONS)
    existing_channels = {
        str(source_definition.config.get("channel", "")).lower()
        for source_definition in definitions
        if source_definition.adapter_type == "telegram_channel"
    }
    for channel in _iter_env_telegram_channels():
        channel_key = channel.lower()
        if channel_key in existing_channels:
            continue
        definitions.append(_build_env_telegram_source(channel))
        existing_channels.add(channel_key)
    return [
        definition
        for definition in definitions
        if definition.source_key not in BLOCKED_SOURCE_KEYS
    ]


SOURCE_DEFINITIONS = get_source_definitions()


def find_source_definition(source_key: str) -> SourceDefinition | None:
    for source_definition in get_source_definitions():
        if source_definition.source_key == source_key:
            return source_definition
    return None


def get_source_definition(source_key: str) -> SourceDefinition:
    source_definition = find_source_definition(source_key)
    if source_definition is not None:
        return source_definition
    raise KeyError(f"Unknown source_key: {source_key}")
